In [44]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [91]:
cust_info = pd.read_parquet('Parquets/cust_info.parquet')
credit_card = pd.read_parquet('Parquets/credit_card.parquet')
debit_card = pd.read_parquet('Parquets/debit_card.parquet')
digital_transact = pd.read_parquet('Parquets/digital_transact.parquet')
instapay_incoming = pd.read_parquet('Parquets/instapay_incoming.parquet')
instapay_outgoing = pd.read_parquet('Parquets/instapay_outgoing.parquet')

In [55]:
pd.set_option('display.float_format', '{:.3f}'.format)

In [64]:
cust_info.head()

,cust_num,province,region,education,age,tenure,business_owner,digital_flag,income_source,idv_or_org,segment,subsegment,gender,marital_status
0,11712.654,BENGUET,CORDILLERA ADMINISTRATIVE REGION (CAR),Unspecified,20.000,1.833,N,DIGITAL,ALLOWANCE,1,3,CORE MASS,MALE,SINGLE
1,436.605,BENGUET,CORDILLERA ADMINISTRATIVE REGION (CAR),Unspecified,21.000,4.250,N,Unspecified,SALARY,1,3,CORE MASS,FEMALE,SINGLE
2,921.989,BENGUET,CORDILLERA ADMINISTRATIVE REGION (CAR),Unspecified,23.000,2.000,N,TRADITIONAL,ALLOWANCE,1,3,CORE MASS,MALE,SINGLE
3,1119.635,BENGUET,CORDILLERA ADMINISTRATIVE REGION (CAR),LOW,13.000,5.583,N,TRADITIONAL,ALLOWANCE,1,3,CORE MASS,MALE,SINGLE
4,1709.756,BENGUET,CORDILLERA ADMINISTRATIVE REGION (CAR),Unspecified,20.000,1.250,N,DIGITAL,SALARY,1,3,CORE MASS,FEMALE,SINGLE

In [68]:
cust_info['tenure'].describe()

count   46150.000
mean        6.281
std         5.241
min         0.083
25%         2.167
50%         5.083
75%         9.000
max        30.417
Name: tenure, dtype: float64

In [18]:
credit_card.head()

,cust_num,merch_group,date,amount,channel,merch_name,country
0,3016.966026,Retail Outlet Services,2023-04-01,3211.528727,POS-RETAIL PURCHASE,MERCHANT 1,PH
1,3016.966026,Clothing Stores,2023-04-01,3982.218215,POS-RETAIL PURCHASE,MERCHANT 2,PH
2,3016.966026,Miscellaneous Stores,2023-04-18,872.539734,POS-RETAIL PURCHASE,MERCHANT 3,PH
3,3016.966026,Miscellaneous Stores,2023-04-27,390.082187,POS-RETAIL PURCHASE,MERCHANT 4,PH
4,3016.966026,Retail Outlet Services,2023-04-29,4956.055464,ONLINE-RETAIL PURCHASE,MERCHANT 5,PH

In [101]:
cc_sub = credit_card.loc[:, ~credit_card.columns.isin(['merch_name','country'])]

In [112]:
cc_sub.head()

,cust_num,merch_group,date,amount,channel
0,3016.966,Retail Outlet Services,2023-04-01,3211.529,POS-RETAIL PURCHASE
1,3016.966,Clothing Stores,2023-04-01,3982.218,POS-RETAIL PURCHASE
2,3016.966,Miscellaneous Stores,2023-04-18,872.540,POS-RETAIL PURCHASE
3,3016.966,Miscellaneous Stores,2023-04-27,390.082,POS-RETAIL PURCHASE
4,3016.966,Retail Outlet Services,2023-04-29,4956.055,ONLINE-RETAIL PURCHASE

In [113]:
cc_sub_agg = cc_sub.groupby('cust_num').agg(
    total_spent = ('amount','sum')
)

cc_sub_agg.head()

          total_spent
cust_num
206.451    139134.165
362.331     37549.343
565.599     20881.382
658.972     17923.512
726.734     14729.502

In [83]:
cc_sub['merch_group'].value_counts()

merch_group
Retail Outlet Services                                14237
Miscellaneous Stores                                  11496
Transportation Services                                1869
Unspecified                                            1568
Utility Services                                       1017
Clothing Stores                                         930
Airlines                                                579
Lodging                                                 482
Professional Services and Membership Organizations      424
Business Services                                       337
Government Services                                     138
Agricultural Services                                    41
Contracted Services                                       8
Name: count, dtype: int64

In [96]:
cc_sub['amount'].describe()

count    33126.000
mean      3244.013
std      12937.494
min          0.000
25%        406.336
50%        963.777
75%       2285.339
max     800021.252
Name: amount, dtype: float64

In [ ]:
debit_card.head()

      cust_num channel       date   time        amount
0  3659.137057     POS 2023-04-01  39958  30001.039678
1  3659.137057     POS 2023-04-04  51349  20001.662634
2  3659.137057     POS 2023-04-05  42803  22001.514584
3  3659.137057     POS 2023-04-06  51455  30001.529392
4  3659.137057     POS 2023-04-11  62752  22001.092602

In [95]:
dc_sub = debit_card.loc[:, debit_card.columns != 'time']

In [88]:
dc_sub['amount'].describe()

count   369594.000
mean      3239.903
std       4704.812
min          0.000
25%          3.505
50%       1217.695
75%       5001.463
max     141322.807
Name: amount, dtype: float64

In [92]:
digital_transact.head()

   cust_num   amount channel      tran_type        date      time
0  4418.325 2000.886  MOBILE       E-WALLET  2023-04-01  07:55:10
1  4418.325 2000.408  MOBILE       E-WALLET  2023-04-01  07:54:01
2  4418.325 9829.357  MOBILE  BILLS PAYMENT  2023-04-14  11:04:20
3  7356.781 2000.576  MOBILE       E-WALLET  2023-04-11  09:41:43
4 10768.576  100.668     WEB       E-WALLET  2023-04-02  20:36:51

In [56]:
digital_transact['amount'].describe()

count    174613.000
mean       3383.496
std        9076.471
min           0.000
25%         406.637
50%        1000.800
75%        3000.917
max     1200000.278
Name: amount, dtype: float64

In [47]:
instapay_incoming.head()

   cust_num       date   time   amount bpi_acct_type src_bank_name
0   5713.40 2023-04-01  73591 12299.24            SA         LEMUR
1   5713.40 2023-04-05  44714  2499.42            SA         HUMAN
2   5713.40 2023-04-24  46302   748.74            SA         HUMAN
3   5713.40 2023-04-29  40612  1799.14            SA         HUMAN
4   5713.40 2023-04-29  24021  1499.63            SA         HUMAN

In [106]:
ip_inc_sub = instapay_incoming.loc[:, ~instapay_incoming.columns.isin(['time','src_bank_name'])]

In [102]:
ip_inc_sub['amount'].describe()

count   80042.000
mean     7222.707
std      9930.188
min         0.000
25%      1399.106
50%      3499.220
75%      8899.651
max     50000.127
Name: amount, dtype: float64

In [103]:
ip_inc_sub['bpi_acct_type'].value_counts()

bpi_acct_type
SA    79248
CA      794
Name: count, dtype: int64

In [60]:
instapay_outgoing.head()

   cust_num       date   time   amount channel rcv_bank_name
0 12844.856 2023-04-01  68284  999.859  MOBILE         HUMAN
1 12844.856 2023-04-01  70887 1999.473  MOBILE         HUMAN
2 12844.856 2023-04-02  14934 5099.595  MOBILE         HUMAN
3 12844.856 2023-04-02  14025 1799.586  MOBILE         HUMAN
4 12844.856 2023-04-04   5845 4299.349  MOBILE         HUMAN

In [109]:
ip_out_sub = instapay_outgoing.loc[:, ~instapay_outgoing.columns.isin(['time','rcv_bank_name'])]

In [110]:
ip_out_sub['amount'].describe()

count   40829.000
mean     6672.681
std     10459.537
min         0.000
25%       974.524
50%      2499.488
75%      7199.141
max     50000.763
Name: amount, dtype: float64

In [111]:
ip_out_sub['channel'].value_counts()

channel
MOBILE    40436
ONLINE      393
Name: count, dtype: int64

In [ ]:
# merge DFs into one main DF
merge_1 = cust_info.merge()